name: Reward Timer v1.0
version: 1.0
main: io.github.synthh.rewardtimer.RewardTimer
description: A plugin that rewards players for playing on the server.

commands:
   xptstart:
      usage: /<command>
      description: (Re-)starts the plugin's features.
   xptstop:
      usage: /<command>
      description: Disables the plugin's features.
   xptsetxp:
      usage: /<command>
      description: Set the amount of XP received.
   xptsettimer:
      usage: /<command>
      description: Set the time interval between reward drops. (1200 = 1 minute)