name: Reward Timer v1.0.0
version: 1.0.0
main: io.github.synthh.rewardtimer.RewardTimer
description: A plugin that rewards players for playing on the server.

commands:
  rtstart:
    usage: /<command>
    description: (Re-)enables plugin features.
    permission: RewardTimer.rtstart
    permission-message: You do not have <permission>.
  rtstop:
    usage: /<command>
    description: Disables plugin features.
    permission: RewardTimer.rtstop
    permission-message: You do not have <permission>.
  rtsetxp:
    usage: /<command> [xp]
    description: Sets the amount of XP to be given. (1 = one level)
    permission: RewardTimer.rtsetxp
    permission-message: You do not have <permission>.
  rtsettimer:
    usage: /<command> [interval]
    description: Sets the amount of time between reward drops. (1200 = one minute)
    permission: RewardTimer.rtsettimer
    permission-message: You do not have <permission>.
      
permissions:
  RewardTimer.*:
    description: Gives access to all RewardTimer commands.
    children:
      RewardTimer.rtstart: true
      RewardTimer.rtstop: true
      RewardTimer.rtsetxp: true
      RewardTimer.rtsettimer: true
  RewardTimer.rtstart:
    description: (Re-)enables RewardTimer features.
    default: op
  RewardTimer.rtstop:
    description: Disables RewardTimer features.
    default: op
  RewardTimer.rtsetxp:
    description: Sets the amount of XP that is given at given intervals ("1" is one level).
    default: op
  RewardTimer.rtsettimer:
    description: Sets the time interval between reward drops ("1200" is one minute).
    default: op
   
      